#!/usr/bin/env python3
"""Generate or check the public MCP tool catalog from registered contracts."""

from __future__ import annotations

import argparse
import asyncio
from pathlib import Path

from mcp_erpnext.contracts.audit import audit_tool_contracts
from mcp_erpnext.contracts.registry import TOOL_CONTRACTS
from mcp_erpnext.mcp_server import create_mcp


APP_ROOT = Path(__file__).resolve().parents[1]
CATALOG_PATH = APP_ROOT / "docs" / "TOOLS.md"


def _model_name(model: object | None) -> str:
	return getattr(model, "__name__", "Legacy public schema")


def _schema_summary(schema: dict) -> str:
	required = schema.get("required", [])
	return f"Required: {', '.join(f'`{field}`' for field in required) or 'none'}"


async def render_catalog() -> str:
	"""Render the catalog from the actual FastMCP registration and declaration metadata."""
	tools = await create_mcp().list_tools()
	issues = audit_tool_contracts(tools)
	if issues:
		raise RuntimeError("\n".join(issues))
	by_name = {tool.name: tool for tool in tools}
	lines = [
		"# MCP Tool Catalog",
		"",
		"<!-- Generated by scripts/generate_tool_catalog.py; do not edit manually. -->",
		"",
		"This catalog is generated from the source-registered MCP tools and their contract metadata. "
		"`tools/list` remains the authoritative machine-readable schema.",
		"",
		"| Tool | Domain | Operation | Side effect | Approval | Contract status |",
		"| --- | --- | --- | --- | --- | --- |",
	]
	for contract in TOOL_CONTRACTS.values():
		status = "Legacy migration inventory" if contract.legacy else "Explicit typed contract"
		lines.append(
			f"| `{contract.name}` | {contract.domain} | {contract.operation.value.title()} | "
			f"{contract.side_effect.value} | {'Trusted human approval required' if contract.approval_required else 'Not a final write'} | {status} |"
		)

	for contract in TOOL_CONTRACTS.values():
		tool = by_name[contract.name]
		lines.extend(
			[
				"",
				f"## `{contract.name}`",
				"",
				contract.purpose,
				"",
				f"- Input: `{_model_name(contract.input_model)}` — {_schema_summary(tool.inputSchema)}",
				f"- Output: `{_model_name(contract.output_model)}`"
				+ (
					f"; resolution states: {', '.join(f'`{state}`' for state in contract.resolution_states)}"
					if contract.resolution_states
					else ""
				)
				+ (
					"; published through MCP `outputSchema`."
					if tool.outputSchema and not contract.legacy
					else "; legacy response shape pending focused migration."
				),
				f"- Side effect: `{contract.side_effect.value}`; approval "
				+ (
					f"requires server-verified human approval through `{contract.approval_guard}` before the final write."
					if contract.approval_required
					else "does not perform the final write."
				),
			]
		)
	return "\n".join(lines) + "\n"


def main() -> None:
	parser = argparse.ArgumentParser(description=__doc__)
	parser.add_argument("--check", action="store_true", help="fail when docs/TOOLS.md is stale")
	args = parser.parse_args()
	content = asyncio.run(render_catalog())
	if args.check:
		if not CATALOG_PATH.exists() or CATALOG_PATH.read_text() != content:
			raise SystemExit("docs/TOOLS.md is stale; run scripts/generate_tool_catalog.py")
		return
	CATALOG_PATH.write_text(content)


if __name__ == "__main__":
	main()
