#!/usr/bin/env python3
"""Generate or check the public MCP tool catalog from registered contracts."""

from __future__ import annotations

import argparse
import asyncio
from dataclasses import replace
from pathlib import Path

from mcp_erpnext.contracts.audit import audit_tool_contracts
from mcp_erpnext.contracts.registry import TOOL_CONTRACTS
from mcp_erpnext.mcp_server import create_mcp
from mcp_erpnext.settings import MCPProfile, MCPSettings


APP_ROOT = Path(__file__).resolve().parents[1]
CATALOG_PATH = APP_ROOT / "docs" / "TOOLS.md"


def _model_name(model: object | None) -> str:
	return getattr(model, "__name__", "Legacy public schema")


def _schema_summary(schema: dict) -> str:
	required = schema.get("required", [])
	return f"Required: {', '.join(f'`{field}`' for field in required) or 'none'}"


def _annotation_summary(name: str) -> str:
	annotations = TOOL_CONTRACTS[name].mcp_annotations()
	return ", ".join(
		f"`{field}={str(value).lower()}`"
		for field, value in annotations.model_dump(by_alias=True, exclude_none=True).items()
		if field != "title"
	)


async def render_catalog() -> str:
	"""Render the catalog from the actual FastMCP registration and declaration metadata."""
	lines = [
		"# MCP Tool Catalog",
		"",
		"<!-- Generated by scripts/generate_tool_catalog.py; do not edit manually. -->",
		"",
		"This catalog is generated from the profile-registered MCP tools and their contract metadata. "
		"`tools/list` remains the authoritative machine-readable schema.",
		"",
		"Each public tool publishes both project-specific `mcp_erpnext` metadata and standard MCP "
		"safety annotations. `ToolContract` is the single source of truth for both layers; host "
		"approval policy remains separate from server-enforced business approval.",
		"",
		"The generic PDF capability is documented in [MCP_DOCUMENT_PDF.md](architecture/MCP_DOCUMENT_PDF.md), "
		"and the generic email capability is documented in [MCP_DOCUMENT_EMAIL.md](architecture/MCP_DOCUMENT_EMAIL.md).",
		"",
	]
	for profile in MCPProfile:
		settings = replace(MCPSettings.from_environment(), profile=profile)
		tools = await create_mcp(settings).list_tools()
		issues = audit_tool_contracts(tools)
		if issues:
			raise RuntimeError("\n".join(issues))
		by_name = {tool.name: tool for tool in tools}
		lines.extend([
			"",
			f"## {profile.value.title()} profile",
			"",
			"| Tool | Domain | Operation | Side effect | MCP annotations | Interaction | Approval | Contract status |",
			"| --- | --- | --- | --- | --- | --- | --- | --- |",
		])
		for name in by_name:
			contract = TOOL_CONTRACTS[name]
			status = "Legacy migration inventory" if contract.legacy else "Explicit typed contract"
			lines.append(
				f"| `{contract.name}` | {contract.domain} | {contract.operation.value.title()} | "
				f"{contract.side_effect.value} | {_annotation_summary(contract.name)} | "
				f"{', '.join(kind.value for kind in contract.interaction_kinds) or 'None'} | "
				f"{'Explicit approval required; server policy enforced' if contract.approval_required else 'Not a final write'} | {status} |"
			)
		for name, tool in by_name.items():
			contract = TOOL_CONTRACTS[name]
			lines.extend([
				"",
				f"### `{contract.name}`",
				"",
				contract.purpose,
				"",
				f"- Input: `{_model_name(contract.input_model)}` — {_schema_summary(tool.inputSchema)}",
				f"- Output: `{_model_name(contract.output_model)}`"
				+ (f"; resolution states: {', '.join(f'`{state}`' for state in contract.resolution_states)}" if contract.resolution_states else "")
				+ ("; published through MCP `outputSchema`." if tool.outputSchema and not contract.legacy else "; legacy response shape pending focused migration."),
				f"- Side effect: `{contract.side_effect.value}`; approval "
				+ (f"requires explicit approval through `{contract.approval_guard}` before the final write; the server-selected approval policy enforces the trust requirement." if contract.approval_required else "does not perform the final write."),
				f"- MCP annotations: {_annotation_summary(contract.name)}.",
				("- Interaction: " + ", ".join(f"`{kind.value}`" for kind in contract.interaction_kinds) + "; emitted only for the documented result states." if contract.interaction_kinds else "- Interaction: none declared."),
			])
	return "\n".join(lines) + "\n"


def main() -> None:
	parser = argparse.ArgumentParser(description=__doc__)
	parser.add_argument("--check", action="store_true", help="fail when docs/TOOLS.md is stale")
	args = parser.parse_args()
	content = asyncio.run(render_catalog())
	if args.check:
		if not CATALOG_PATH.exists() or CATALOG_PATH.read_text() != content:
			raise SystemExit("docs/TOOLS.md is stale; run scripts/generate_tool_catalog.py")
		return
	CATALOG_PATH.write_text(content)


if __name__ == "__main__":
	main()
